# Generated by Django 4.0.5 on 2022-12-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_money',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
